# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

movies = [
    { title: "Black Panther", description: "After the death of his father, T'Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T'Challa's mettle as king -- and as Black Panther -- gets tested when he's drawn into a conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people.", director: "Ryan Coogler", runtime: "2h 15m", year: 2018, rating: "PG-13", image: "https://i2.wp.com/superheronews.com/wp-content/uploads/2017/10/BlackPanther59e4e6c10eaf4.jpg?fit=1688%2C2500&quality=80&strip=info&ssl=1"},
    { title: "A Quiet Place", description: "In a post-apocalyptic world, a family must navigate their lives in silence after mysterious creatures that hunt by sound threaten their survival. If they hear you, they hunt you.", director: "John Krasinski", runtime: "1h 31m", year: 2018, rating: "PG-13", image: "http://www.impawards.com/2018/posters/quiet_place.jpg"},
    { title: "Avengers: Infinity War", description: "The Avengers unite to battle their most powerful enemy yet -- the evil Thanos. On a mission to collect all six Infinity Stones, Thanos plans to use the artifacts to inflict his twisted will on reality. The fate of the planet and existence itself has never been more uncertain as everything the Avengers have fought for has led up to this moment.", director: "Anthony Russo + Joe Russo", runtime: "2h 40m", year: 2018, rating: "PG-13", image: "https://i.redd.it/gnv94oll6im01.jpg"},
    { title: "Incredibles 2", description: "In Incredibles 2, Helen is called on to lead a campaign to bring Supers back, while Bob navigates the day-to-day heroics of “normal” life at home with Violet, Dash and baby Jack-Jack—whose superpowers are about to be discovered. Their mission is derailed, however, when a new villain emerges with a brilliant and dangerous plot that threatens everything. But the Parrs don’t shy away from a challenge, especially with Frozone by their side. That’s what makes this family so Incredible.", director: "Brad Bird", runtime: "2h 5m", year: 2018, rating: "PG", image: "http://www.impawards.com/2018/posters/incredibles_two_ver11.jpg"},
    { title: "Mission: Impossible - Fallout", description: "Ethan Hunt and the IMF team join forces with CIA assassin August Walker to prevent a disaster of epic proportions. Arms dealer John Lark and a group of terrorists known as the Apostles plan to use three plutonium cores for a simultaneous nuclear attack on the Vatican, Jerusalem and Mecca, Saudi Arabia. When the weapons go missing, Ethan and his crew find themselves in a desperate race against time to prevent them from falling into the wrong hands.", director: "Christopher McQuarrie", runtime: "2h 28m", year: 2018, rating: "PG-13", image: "https://m.media-amazon.com/images/M/MV5BMTk3NDY5MTU0NV5BMl5BanBnXkFtZTgwNDI3MDE1NTM@._V1_.jpg"},
    { title: "BlacKkKlansman", description: "It’s the early 1970s, and Ron Stallworth (John David Washington) is the first African-American detective to serve in the Colorado Springs Police Department. Determined to make a name for himself, Stallworth bravely sets out on a dangerous mission: infiltrate and expose the Ku Klux Klan. The young detective soon recruits a more seasoned colleague, Flip Zimmerman (Adam Driver), into the undercover investigation of a lifetime. Together, they team up to take down the extremist hate group as the organization aims to sanitize its violent rhetoric to appeal to the mainstream.", director: "Spike Lee", runtime: "2h 16m", year: 2018, rating: "R", image: "https://m.media-amazon.com/images/M/MV5BMjUyOTE1NjI0OF5BMl5BanBnXkFtZTgwMTM4ODQ5NTM@._V1_.jpg"}
]

Movie.delete_all
Movie.create(movies)